---
# tasks file for install-singularity

- name: Install dependencies
  apt:
    name: 
      - build-essential
      - automake
      - libssl-dev
      - uuid-dev
      - libtool
      - m4
      - libgpgme11-dev
      - squashfs-tools
      - libseccomp-dev
      - libarchive-dev
      - wget
      - debootstrap
      - pkg-config
      - git
      - python
      - cryptsetup
    state: present
    update_cache: true

- name: Add repo
  apt_repository:
    repo: ppa:longsleep/golang-backports

- name: Install golang
  apt:
    name: 
      - golang-go
    state: present
    update_cache: true

- name: Download files
  command: git clone https://github.com/sylabs/singularity.git
  args:
    chdir: /tmp

- name: Fetch
  command: git fetch --all
  args:
    chdir: /tmp/singularity

- name: Checkout
  command: git checkout 2.6.1
  args:
    chdir: /tmp/singularity

- name: Configure
  command: ./autogen.sh
  args:
    chdir: /tmp/singularity

- name: Configure
  command: ./configure --prefix=/usr/local
  args:
    chdir: /tmp/singularity

- name: Make
  make:
    chdir: /tmp/singularity/

- name: Make install
  make:
    chdir: /tmp/singularity/
    target: install

- name: Link
  command: ldconfig

- name: Cleanup
  file:
    path: /tmp/singularity
    state: absent