---
# tasks file for install-singularity

- name: Install dependencies
  apt:
    name: 
      - build-essential
      - libssl-dev
      - uuid-dev
      - libgpgme11-dev
      - squashfs-tools
      - libseccomp-dev
      - wget
      - pkg-config
    state: present
    update_cache: true

- name: Add repo
  apt_repository:
    repo: ppa:longsleep/golang-backports

- name: Install golang
  apt:
    name: 
      - golang-go=2:1.13~1longsleep1+xenial
    state: present
    update_cache: true

- name: Install 'dep'
  command: go get -u github.com/golang/dep/cmd/dep
  environment:
    GO111MODULE: "off"

- name: Remove singularity repo if it already exists
  file:
    path: /usr/lib/go/src/github.com/sylabs/singularity
    state: absent

- name: Create /usr/lib/go/src/github.com/sylabs if it does not exist
  file:
    path: /usr/lib/go/src/github.com/sylabs
    state: directory
    mode: '0755'

- name: Download repo
  command: git clone https://github.com/sylabs/singularity.git
  args:
    chdir: /usr/lib/go/src/github.com/sylabs  

- name: Checkout
  command: git checkout v{{version}}
  args:
    chdir: /usr/lib/go/src/github.com/sylabs/singularity

- name: Configure
  command: ./mconfig --prefix={{install_directory}}
  args:
    chdir: /usr/lib/go/src/github.com/sylabs/singularity

- name: Make
  command: make -C ./builddir
  args:
    chdir: /usr/lib/go/src/github.com/sylabs/singularity
  environment:
    GO111MODULE: "off"

- name: Make install
  command: make -C ./builddir install
  args:
    chdir: /usr/lib/go/src/github.com/sylabs/singularity
  become: true
  environment:
    GO111MODULE: "off"

- name: Link
  command: ldconfig

- name: Cleanup
  file:
    path: /usr/lib/go/src/github.com/sylabs/singularity
    state: absent
  
- name: Add bin dir to system-wide $PATH.
  copy:
    dest: /etc/profile.d/singularity-{{version}}.sh
    content: 'PATH=$PATH:{{install_directory}}/bin'