heat_template_version: "2018-08-31"
description: "version 2017-09-01 created by HOT Generator at Mon, 25 Nov 2019 18:49:45 GMT."

parameters:
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instances
    default: "Trevor Surface id_rsa"

  bootable_snapshot_id:
    type: string
    label: Snapshot ID
    description: ID of the snapshot used to boot instances
    default: "ec58d12c-be0c-406e-a3d1-a9b7d483cb85"

  network_name:
    type: string
    label: Network Name
    description: Name of network to be used for compute instances
    default: "nsg-devs_network"

resources:

  # Variables that the user shuold not be able to change
  floating_network:
    type: OS::Heat::Value
    properties:
      type: string
      value: 96d88aaf-1ef4-4d34-8aeb-3687c4f9dcc3


  # Resource that are created by this template

  server_1:
    type: "OS::Nova::Server"
    properties:
      networks: [{"port": { get_resource: port_1}, "floating_ip": { get_resource: floating_ip_1 } }]
      flavor: "m1.medium"
      block_device_mapping: [{"snapshot_id": { get_param: bootable_snapshot_id }, "device_name": "vda"}]
      name: "mpi-1"
      key_name: { get_param: key_name }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo "$PRIVATE_KEY" > /home/ubuntu/.ssh/id_rsa
            echo "$PUBLIC_KEY" >> /home/ubuntu/.ssh/authorized_keys
            chown ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa
            chmod 600 /home/ubuntu/.ssh/id_rsa
          params:
            $PRIVATE_KEY: { get_attr: [key_pair, private_key] }
            $PUBLIC_KEY: { get_attr: [key_pair, public_key] }

  server_2:
    type: "OS::Nova::Server"
    properties:
      networks: [{"port": { get_resource: port_2}, "floating_ip": { get_resource: floating_ip_2 } }]
      flavor: "m1.medium"
      block_device_mapping: [{"snapshot_id": { get_param: bootable_snapshot_id }, "device_name": "vda"}]
      name: "mpi-2"
      key_name: { get_param: key_name }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo "$PRIVATE_KEY" > /home/ubuntu/.ssh/id_rsa
            echo "$PUBLIC_KEY" >> /home/ubuntu/.ssh/authorized_keys
            chown ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa
            chmod 600 /home/ubuntu/.ssh/id_rsa
          params:
            $PRIVATE_KEY: { get_attr: [key_pair, private_key] }
            $PUBLIC_KEY: { get_attr: [key_pair, public_key] }

  security_group_ssh:
    type: "OS::Neutron::SecurityGroup"
    properties:
      rules:
        - direction: ingress
          ethertype: IPv4
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - direction: ingress
          ethertype: IPv4
          protocol: icmp

  floating_ip_1:
    type: "OS::Neutron::FloatingIP"
    properties:
      floating_network: { get_attr: [floating_network, value] }

  floating_ip_2:
    type: "OS::Neutron::FloatingIP"
    properties:
      floating_network: { get_attr: [floating_network, value] }

  port_1:
    type: "OS::Neutron::Port"
    properties:
      admin_state_up: true
      network: { get_param: network_name }
      security_groups: [{ get_resource: security_group_ssh }]

  port_2:
    type: "OS::Neutron::Port"
    properties:
      admin_state_up: true
      network: { get_param: network_name }
      security_groups: [{ get_resource: security_group_ssh }]

  key_pair:
    type: "OS::Nova::KeyPair"
    properties:
      name: "mpi-shared-key"
      save_private_key: true


outputs:
  KeyPair_1_private_key:
    description: "The private_key of KeyPair_1."
    value: "{ get_attr: [key_pair, private_key] }"
