---
# tasks file for install-openmpi

- name: Install open mpi dependencies
  apt:
    name:
      - build-essential
      - libcr-dev
    state: present
    update_cache: true

- name: Download/Unarchive open mpi tar file
  unarchive:
    src: https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.4.tar.gz
    dest: /tmp
    remote_src: yes

- name: Configure
  command: ./configure --prefix=/usr/local
  args:
    chdir: /tmp/openmpi-3.1.4

- name: Make
  make:
    chdir: /tmp/openmpi-3.1.4
    target: install

- name: Link
  command: ldconfig

- name: Cleanup
  file:
    path: /tmp/openmpi-3.1.4
    state: absent