---
# tasks file for install-openmpi

- name: Install open mpi dependencies
  apt:
    name:
      - build-essential
      - libcr-dev
    state: present
    update_cache: true

- name: Download/Unarchive open mpi tar file
  unarchive:
    src: https://download.open-mpi.org/release/open-mpi/v{{version_major}}.{{version_minor}}/openmpi-{{version}}.tar.gz
    dest: /tmp
    remote_src: yes

- name: Configure
  command: ./configure --prefix={{install_directory}}
  args:
    chdir: /tmp/openmpi-{{version}}

- name: Make
  make:
    chdir: /tmp/openmpi-{{version}}
    target: install

- name: Link
  command: ldconfig

- name: Cleanup
  file:
    path: /tmp/openmpi-{{version}}
    state: absent

- name: Add bin dir to system-wide $PATH.
  copy:
    dest: /etc/profile.d/openmpi-{{version}}.sh
    content: 'PATH=$PATH:{{install_directory}}/bin'